# Generated by Django 3.1.1 on 2020-09-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupTask', '0001_initial'),
        ('Task', '0002_groupshared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupshared',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupTask.grouptask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupTask.grouptask'),
        ),
        migrations.AlterField(
            model_name='typetask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupTask.grouptask'),
        ),
        migrations.DeleteModel(
            name='GroupTask',
        ),
    ]
